### ISSUE TITLE
AqSolDB - dataset for solubility, ignored intentionally?

### ISSUE THREAD

**Issue by salman-moh** [MolecularAI/Chemformer#15]
Hi, 
The same regression fine-tuning of 3 tasks simulataneously but adding the other solubility datasets as well from [here ](https://github.com/Mengjintao/SolCuration), but before I go ahead with it, I'm curious if a thought was given to this or were there any disadvantages  to this? maybe because the dataset isnt completely reliable.

Thanks

**Comment by EBjerrum** [comment]
No, didn't know the other dataset.
