### ISSUE TITLE
Small setup.py change

### ISSUE THREAD

**Issue by vthost** [MolecularAI/Chemformer#16]
Hi,
I failed to install Chemformer as module, and it seems to be because `setup.py` is missing `packages=find_packages(exclude=[])`. Could you maybe add that? It would ease our setup considerably. Thank you so much already!

**Comment by SGenheden** [comment]
Hello Veronika.

Would the fix suggested in PR #2 work for you as well? It seems to amount to the same thing? Install all modules.

BR
Samuel

**Comment by vthost** [comment]
Yes, exactly!
