### ISSUE TITLE
Using pretrained ChemFormer to get encoder and decoder outputs

### ISSUE THREAD

**Issue by Vikramank** [MolecularAI/Chemformer#20]
Hello, 
I would like to get the embeddings (output from BART encoder) and separately use the embeddings as an input to the decoder ti get back SMILES string as presented in **step 1 in Figure1 in the paper**. I don't see a direct way, could you please suggest me any methods?

**Comment by EBjerrum** [comment]
You would have to intercept the encode and decode methods of the model. The encode will give you the memory, and you would have to look into how the memory is used with the sampler and decoder.

**Comment by Vikramank** [comment]
Hi @EBjerrum ,
Thanks for the advice. Back tracking the training and evaluation scripts to do the same :) 
Best,
K.Vikraman

**Comment by IvanGarcia7** [comment]
Any update about how to do that?
