### ISSUE TITLE
How to do random generation and Interpolation?

### ISSUE THREAD

**Issue by tinymd** [MolecularAI/Chemformer#21]
Hello,
I have seen that you collaborated with Nvidia on the Megatron version of Chemformer, which can perform interpolation between two given molecules. How is this implemented?
![1690714334(1)](https://github.com/MolecularAI/Chemformer/assets/16483616/921b9d54-9ec1-47cb-83ed-435d277bbbd7)
The source link for this image is as follows. https://github.com/NVIDIA/cheminformatics/blob/master/tutorial/Tutorial.md

**Comment by rssrwn** [comment]
You’re right that Nvidia’s model was based on Chemformer but the interpolation code is part of their project, rather than being implemented by the Chemformer model. I think you’re best to ask Nvidia directly.

**Comment by EBjerrum** [comment]
Chemformer wasn't really aimed at being a latent space based model, so if you really want to do interpolation, there are probably better models for that.
