### ISSUE TITLE
models.py file is not in the repository?

### ISSUE THREAD

**Issue by Ontos46** [MolecularAI/Chemformer#22]
Apologies if that's a dumb question, I wanted to look into the models.py file from readme but wasn't able to find it in this repository. Could you, please, help me with this? The readme says the following: "Models: The models.py file contains a Pytorch Lightning implementation of the BART language model, as well as Pytorch Lightning implementations of models for downstream tasks.", but I couldn't locate the models.py file.

**Comment by EBjerrum** [comment]
Ah, I think it has been moved around/refactored. The base model for pretraining is in https://github.com/MolecularAI/Chemformer/blob/main/molbart/models/pre_train.py

finetuning is demonstrated with the scripts in https://github.com/MolecularAI/Chemformer/blob/main/example_scripts/fine_tune.sh

and theres an example of using the pretrained encoder for a regression model in 
https://github.com/MolecularAI/Chemformer/blob/main/example_scripts/finetune_regression/finetuneRegr.py
