### ISSUE TITLE
Issues finding the correct dataset

### ISSUE THREAD

**Issue by princeklat03** [MolecularAI/Chemformer#30]
I have been unable to find some of the datasets that appear to be essential for the running of the code, such as the "uspto_50.txt" file.  I converted the uspto_50.pickle to text in a tabulated format and changed the "reactants_mol" and "products_mol" columns to "reactants" and "products", respectively, but then the program could not find a sequence length column: KeyError: 'This dataset does not store any sequence lengths'. 

Similarly, while while running predict.sh, I couldn't find the "bart_vocab_downstream.**txt"** file, only  "bart_vocab_downstream.**json** file is available.

Could you please point me to the correct files: uspto_50.**txt** and bart_vocab_downstream.**txt**?

**Comment by princeklat03** [comment]
Finding correct file format

**Comment by anniewesterlund** [comment]
Hi!
The file format of uspto_50_test.txt should be a text file with USPTO50k reactants, on the format:
```
CCO.C
C.C
...
```
You can convert the (test set-) reactants molecules in your USPTO50k dataset to SMILES and save to a text file. Then you can use this as input. 
The `bart_vocab_downstream.txt` is now replaced by `bart_vocab_downstream.json`.
