### ISSUE TITLE
Cannot import name 'DeepSpeedPlugin' from 'pytorch_lightning.plugins'

### ISSUE THREAD

**Issue by nzsimonc** [MolecularAI/Chemformer#34]
Hey all,
I'm trying to use ./example_scripts/fine_tune.sh however, I get the following error when running it
                
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/Chemformer/molbart/fine_tune.py", line 4, in <module>
    import molbart.modules.util as util
  File "/home/user/Chemformer/molbart/modules/util.py", line 13, in <module>
    from pytorch_lightning.plugins import DeepSpeedPlugin
ImportError: cannot import name 'DeepSpeedPlugin' from 'pytorch_lightning.plugins' (/home/user/miniconda3/lib/python3.12/site-packages/pytorch_lightning/plugins/__init__.py). Did you mean: 'DeepSpeedPrecision'?
```

This is using pip3 install pytorch_lightning   
when I researched it pytorch_lightning had DeepSpeedPlugin in v1.9.4 - but that version doesn't want to play nice either and it's really old.

Is there something I've missed in my setup or something? 

The process I followed was install miniconda then
git clone https://github.com/MolecularAI/Chemformer
cd Chemformer/
conda env create -f env.yaml
conda activate chemformer

then just run ./example_scripts/fine_tune.sh and install whatever it told me to.

--any help would be amazing, as I've not had any luck for a few days.

**Comment by anniewesterlund** [comment]
The new updated code includes a new installation procedure, among other things. Perhaps this works better for you to setup your environment.

**Comment by nzsimonc** [comment]
The new code at from the end of May worked great!  Many thanks!!
