### ISSUE TITLE
Modify the value for beam size

### ISSUE THREAD

**Issue by TeresaZhou0127** [MolecularAI/Chemformer#39]
Hi Chemformer Team,

I am using Chemformer model on a reaction prediction task. During my training process, when I tried to modify values for n_beams in the config file or even directly in the command line, the value for that parameter is always 1. Could you please provide a more detailed guidance on how to modify hyperparameters for fine-tuning?

Thanks for your great work!

Best

**Comment by anniewesterlund** [comment]
Hi! 

During training, greedy sampling / n_beams=1 is currently enforced in molbart/model/transformer_models.py via `self.val_sampling_alg = "greedy"`. If you are sure that you want to increase n_beams (it will slow down the training), you can change this to `self.val_sampling_alg = "beam"`, and then you will be able to change n_beams in the command line for fine-tuning.

**Comment by TeresaZhou0127** [comment]
Thank you so much for your answer!
