### ISSUE TITLE
published article

### ISSUE THREAD

**Issue by abilsland** [MolecularAI/Chemformer#4]
Not an issue with the code but just letting you know that the pdf link at the accepted Chemformer version in Mach Learn: Sci Technol doesn't actually link to your article. It has your title on the front page but the rest of the pdf is an article called "Physics makes the difference: Bayesian optimization and active learning via augmented Gaussian process" by Ziatdinov et al. Just in case you want to tell the journal to correct it.

**Comment by EBjerrum** [comment]
Thanks for letting me know, the journal has been informed.
