### ISSUE TITLE
Prediction result garbled characters

### ISSUE THREAD

**Issue by llmgpt** [MolecularAI/Chemformer#40]
sh example_scripts/predict.sh 
**input**:[CH3:18][CH2:19][O:20][C:21](=[O:22])[Cl:23].[CH3:1][O:2][c:3]1[cH:4][c:5]2[n:6][c:7]([NH2:8])[c:9]([O:10][CH3:11])[n:12][c:13]2[cH:14][c:15]1[O:16][CH3:17].[cH:24]1[cH:25][cH:26][n:27][cH:28][cH:29]1>>CCOC(=O)Nc1nc2cc(OC)c(OC)cc2nc1OC 8;;21-23-1.0;21-8-1.0
[CH3:1][C:2]([CH3:3])([CH3:4])[O:5][C:6](=[O:7])[c:8]1[cH:9][cH:10][c:11](-[n:12]2[c:13]([CH2:14][CH2:15][C:16](=[O:17])[OH:18])[cH:19][cH:20][c:21]2-[c:22]2[cH:23][cH:24][cH:25][cH:26][cH:27]2)[cH:28][cH:29]1.[CH3:43][C:44](=[O:45])[O-:46].[NH4+:42].[O:30]=[C:31]([n:32]1[cH:33][cH:34][n:35][cH:36]1)[n:37]1[cH:38][cH:39][n:40][cH:41]1>>CC(C)(C)OC(=O)c1ccc(-n2c(CCC(N)=O)ccc2-c2ccccc2)cc1 ;32;16-18-1.0,31-32-1.0,32-33-1.5,32-36-1.5;16-32-1.0
**output**:target_smiles	sampled_smiles_1	sampled_smiles_2	sampled_smiles_3	sampled_smiles_4	sampled_smiles_5	sampled_smiles_6	sampled_smiles_7	sampled_smiles_8	sampled_smiles_9	sampled_smiles_10	loglikelihood_1	loglikelihood_2	loglikelihood_3	loglikelihood_4	loglikelihood_5	loglikelihood_6	loglikelihood_7	loglikelihood_8	loglikelihood_9	loglikelihood_10
CCOC(=O)Nc1nc2cc(OC)c(OC)cc2nc1OC 8;;21-23-1.0;21-8-1.0	[CH-](?[CH-]?)?[CH-]??[CH-]?[CH-]?	[CH-](?[CH-]?)?[CH-]?[CH-]?[CH-]?[CH-]?	[CH-](?[CH-]?)?[CH-]?[CH-]?[CH-]??[CH-]?	[CH-](?[CH-]?)?[CH-]??[CH-]?[CH-]?[CH-]?	[CH-](?[CH-]?)?[CH-]?[CH-]??[CH-]?[CH-]?	[CH-](?[CH-]?)?[CH-]?[CH-]?[CH-]?[CH-]??	[CH-](?[CH-]?)?[CH-]?[CH-]?[CH-]?[CH-]?[CH-]?	[CH-](?[CH-]?)?[CH-]?[CH-]?[CH-]??[CH-]??	[CH-](?[CH-]?)?[CH-]??[CH-]?[CH-]?[CH-]??	[CH-](?[CH-]?)?[CH-]?[CH-]?[CH-]?[CH-]?[CH-]??	-11.003718	-11.439268	-12.237219	-12.283204	-12.283742	-12.429138	-12.836078	-13.358057	-13.410575	-14.117854
CC(C)(C)OC(=O)c1ccc(-n2c(CCC(N)=O)ccc2-c2ccccc2)cc1 ;32;16-18-1.0
**model**:pretrain/combined.ckpt

**Comment by llmgpt** [comment]
Can you provide forecast txt and corresponding model?

**Comment by EBjerrum** [comment]
Not used the code for some time, but I don't think your input should have atommap numbers and explicit hydrogens, be CXsmiles or reaction smarts.

**Comment by llmgpt** [comment]
Why not provide uspto_50_test.txt and saved_models/uspto_50/span_aug/100_epochs/last.ckpt?I just want to test it, because I don't know much about chemistry.I just need the simplest example to understand

**Comment by llmgpt** [comment]
Please tell me where data_path and model_path are.
```
#!/bin/bash

python -m molbart.predict \
  data_path=uspto_50_test.txt \
  vocabulary_path=bart_vocab_downstream.json \
  model_path=saved_models/uspto_50/span_aug/100_epochs/last.ckpt \
  task=forward_prediction \
  output_sampled_smiles=predicted_products.csv \
  batch_size=64 \
  n_beams=10
```

**Comment by llmgpt** [comment]
My input has been modified, but I don't know what this input means. Is there only one reactant? How to judge the result?
```
C1=COCCC1.COC(=O)CCC(=O)c1ccc(O)cc1O
COC(=O)c1cccc(C(=O)O)c1.Nc1cccnc1N
CC(C)(C)OC(=O)NC1CCC(C(=O)O)CC1.CNOC
Nc1ccc(O)cc1.O=[N+]([O-])c1ccc(Cl)nc1Cl
```

**Comment by llmgpt** [comment]
The reactants are separated by .
