### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by FanmengWang** [MolecularAI/Chemformer#9]
hi
I want to know how to get uspto_50.pickle from the origin uspto_50k.csv ?

**Comment by salman-moh** [comment]
Hey, are you also having the issue where the reactants_path is getting read as text file, but we only have a pickle file, kinda what I described #10

**Comment by FanmengWang** [comment]
hi, I still don't solve this problem. I try to do this by myself, however, I can't get the ideal results.

**Comment by SGenheden** [comment]
The pickle file is outputed by the program. You only need to specify reactant SMILES in a text file as input, see #10
